config/routes.rb
Musecruise::Application.routes.draw do
  
  devise_for :users, controllers: { 
    confirmations: 'confirmations', 
    registrations: 'registrations'
  }

  devise_scope :user do
    patch '/confirm' => 'confirmations#confirm'
  end

  resources :users do
    resources :tours
  end

  resources :tours

  patch   'rate_my_tour',         to: 'tours#rate'
  get   'pages/index',  to: 'pages#index'
  
  root  'pages#home'
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
  end
end

app/models/amenity.rb
class Amenity < ActiveRecord::Base

  has_many :tours_amenities
  has_many :tours, through: :tours_amenities
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/tour.rb
class Tour < ActiveRecord::Base

  belongs_to :tourist, class_name: "User", foreign_key: :tourist_id
  has_many :tours_amenities
  has_many :amenities, through: :tours_amenities

  validates :start_date, :end_date, :questions, presence: true
end

app/models/tours_amenity.rb
class ToursAmenity < ActiveRecord::Base

  belongs_to :tour 
  belongs_to :amenity
end

app/models/user.rb
class User < ActiveRecord::Base

  # required setup for rolify gem
  rolify

  # required setup for devise
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # associations
  has_many :tours, as: :tourist, foreign_key: :tourist_id
  has_many :users_tours

  # validations
  validates_presence_of :email
  validates_presence_of :first_name, on: :update
  validates_presence_of :last_name, on: :update
  validates_presence_of :phone, on: :update

  def password_required?
    super if confirmed?
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def full_name
    self.first_name + " " + self.last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  def after_sign_in_path_for(resource)
    new_tour_path
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

  before_action :redirect_confirmed_to_rating, only: [:show]

  def show

    @amenities = Amenity.all
    self.resource = resource_class.find_by_confirmation_token(params[:confirmation_token]) if params[:confirmation_token].present?
    super if resource.nil? or resource.confirmed?
  end

  def confirm
    self.resource = resource_class.find_by_confirmation_token(params[resource_name][:confirmation_token]) if params[resource_name][:confirmation_token].present?
    if resource.update_attributes(params[resource_name].except(:confirmation_token).permit(confirmation_params)) && resource.password_match?
      self.resource = resource_class.confirm_by_token(params[resource_name][:confirmation_token])
      set_flash_message :notice, :confirmed
      sign_in_and_redirect(resource_name, resource)
    else
      render :action => "show"
    end
  end

  def after_confirmation_path_for(resource_name, resource)
    if signed_in?
      new_user_tour_path
    else
      new_session_path(resource_name)
    end
  end

  def redirect_confirmed_to_rating

    if User.find_by(confirmation_token: params[:confirmation_token]).nil?
      redirect_to root_path
    end
  end

private
  
  def confirmation_params
    [:email, :first_name, :last_name, :phone, :password, :password_confirmation]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

    @users = User.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    super
  end

protected
  def after_sign_up_path_for(resource)
    :new_user_tour_path
  end

   def after_inactive_sign_up_path_for(resource)
    session[:previous_url] || root_path
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController

  # before_filter :authenticate_user!
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
    @amenities = Amenity.all
  end

  def edit
    @user = current_user
    @tour = Tour.where(tourist_id: @user.id).last

  end

  def create
    amenity = Amenity.find_by(id: tour_params[:amenities])
    @tour = Tour.new(
      start_date: tour_params[:start_date],
      end_date: tour_params[:end_date],
      questions: tour_params[:questions],
      tourist_id: current_user.id
      )
    if @tour.save
      @tour.tours_amenities.create(amenity_id: amenity.id)
      redirect_to @tour, notice: 'Tour was successfully created.'
      TourRequestMailer.tour_request_notifier(@tour).deliver
      TourConfirmationMailer.notifier(@tour).deliver
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /tours/1
  def update
    if @tour.update(tour_params)
      redirect_to @tour, notice: 'Tour was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /tours/1
  def destroy
    @tour.destroy
    redirect_to tours_url, notice: 'Tour was successfully destroyed.'
  end

  def rate
    @tour = Tour.find_by(id: params[:tour][:tour_id])
    if @tour.update_attributes(rating: params[:tour][:rating])
      redirect_to root_url, notice: "thanks for the feedback"
    else
      render action: 'edit'
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tour_params
      params.require(:tour).permit(:start_date, :end_date, :questions, :amenities)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :update, :destroy]

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'    
    if @user.update_attributes(user_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:role_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    base_title = "MuseCruise"
    if @page_title.nil?
      base_title
    else
      "#{base_title} | #{@page_title} "
    end
  end

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def nav_link_to(text, path)
    class_name = current_page?(path) ? 'active' : ''

    content_tag(:li, class: "#{class_name}") do
      link_to text, path
    end
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_boilerplate_links.html.haml
/ = nav_link_to "about", about_path
/ = nav_link_to "contact", contact_path
/ = nav_link_to "help", help_path
/ = nav_link_to "privacy", privacy_path
/ = nav_link_to "terms", terms_path
/ = nav_link_to "producers", producers_path

app/views/application/_footer.html.haml
.background-white.footer.visible-phone
  .container
    %p.pull-right
      %a#toplink{:href => "#"} Back to top
    %ul#footer-nav.nav.visible-phone
      %hr/
      %h3.centered Menu
      = render 'boilerplate_links'
      = render 'nav_links'
.navbar.navbar-fixed-bottom.hidden-phone
  .navbar-inner
    .container
      .span6.offset3
        %ul.nav
          = nav_link_to "home", root_url
          = render "boilerplate_links"

app/views/application/_head.html.haml
%title= title
%meta{ charset: "utf-8" }
%meta{ content: "width=device-width, initial-scale=1.0", name: "viewport"}
%meta{ content: "", name: "description"}
%meta{ content: "Frederick D. Schoeneman (fred.schoeneman@gmail.com))", name:"author"}/    
= csrf_meta_tags
= stylesheet_link_tag "application", :media => "all"
= javascript_include_tag "application"
= yield(:head)

app/views/application/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/application/_nav_links.html.haml
%ul.nav
  - if user_signed_in?
    %li
      = link_to('Logout', destroy_user_session_path, :method=>'delete')
    %li
      = link_to('Edit account', edit_user_registration_path)
    - if current_user.has_role? :admin
      %li
        = link_to('Admin', users_path)
  - else
    %li
      = link_to('Login', new_user_session_path)

app/views/application/_navigation.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to title, root_url, class: 'brand'
      %a.visible-phone.btn.btn-simple.pull-right{ href: "#footer-nav"}
        %i.icon-th-list
        %b Menu
      %ul.nav.pull-right.hidden-phone
        = render 'nav_links'
            

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
	%head
		= render 'head'
	%body{:class => "#{controller_name} #{action_name}"}
		.container
			= render 'navigation'
			= render 'messages'
		.container
			= yield 
		.container
			= render 'footer' 
   


	- if Rails.env.development?
		= debug(params) 

app/views/pages/home.html.haml
%h2 Sign up for a tour
= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:class => 'form-vertical' }) do |f|
  = f.error_notification
  = display_base_errors resource
  = f.input :email, required: true
  = f.button :submit, 'Sign up', :class => 'btn-primary'
= render "devise/shared/links"

app/views/tours/_form.html.haml
.form-vertical
  = simple_form_for @tour, class: 'form-vertical' do |f|
    .form-inputs
      = f.error_notification
      = display_base_errors resource
      = f.label :start_date
      = f.text_field :start_date
      = f.label :end_date
      = f.text_field :end_date
      = f.label :questions
      = f.text_area :questions
      = f.input :amenities, collection: @amenities

    .form-actions
      = f.button :submit, class: 'btn-primary btn-large'
      

app/views/tours/edit.html.haml
%h2 rate your tour
= simple_form_for(@tour, url: rate_my_tour_path, class: 'form-vertical') do |f|
  .form-inputs
    = f.error_notification
    = display_base_errors resource
    = f.hidden_field :tour_id, value: @tour.id
    = f.input :rating, collection: 1..5

  .form-actions
    = f.button :submit, "rate this tour", class: 'btn-primary btn-large'

app/views/tours/index.html.haml
%h1 Listing tours

%table
  %tr
    %th Start date
    %th End date
    %th Questions
    %th
    %th
    %th

  - @tours.each do |tour|
    %tr
      %td= tour.start_date
      %td= tour.end_date
      %td= tour.questions
      %td= link_to 'Show', tour
      %td= link_to 'Edit', edit_tour_path(tour)
      %td= link_to 'Destroy', tour, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tour', new_tour_path

app/views/tours/new.html.haml
%h1 New tour

= render 'form'

= link_to 'Back', tours_path

app/views/tours/show.html.haml
%p#notice= notice

%p
  %b Start date:
  = @tour.start_date
%p
  %b End date:
  = @tour.end_date
%p
  %b Questions:
  = @tour.questions

= link_to 'Edit', edit_tour_path(@tour)
\|
= link_to 'Back', tours_path

app/views/users/_user.html.haml
.modal{id: "role-options-#{user.id}", style: "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", href: "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Name
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.full_name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", href: "#role-options-#{user.id}", type: "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p first name: #{@user.first_name}
%p last name: #{@user.last_name}
%p email: #{@user.email}
%p ip: #{@user.last_sign_in_ip}